cqfd: style: use curve bracket when necessary
Most of the codebase uses bracket if necessary (variable substituion...)
and do not use them if not necessary.

However, unnecessary brackets are used at some places.

This replaces the few piece of code using unnecessary brakets.

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -172,7 +172,7 @@ image_exists_locally() {
 #
 # - Your project's source directory is always mapped to $cqfd_user_cwd
 #
-# - Your ~/.ssh directory is mapped to ~${cqfd_user}/.ssh to provide
+# - Your ~/.ssh directory is mapped to ~$cqfd_user/.ssh to provide
 #   access to the ssh keys (your build may pull authenticated git
 #   repos for example).
 #
@@ -265,10 +265,10 @@ docker_run() {
 		for group in "${array[@]}"; do
 			# optional groupd id specified ("name:123")
 			if echo "$group" | grep -qE ":[0-9]+$"; then
-				CQFD_GROUPS+="${group} "
+				CQFD_GROUPS+="$group "
 			else
 				id=$(awk -F: "\$1 == \"$group\" { print \$3 }" /etc/group)
-				CQFD_GROUPS+="${group}:${id} "
+				CQFD_GROUPS+="$group:$id "
 			fi
 		done
 	fi
@@ -450,7 +450,7 @@ mkdir -p "$cqfd_user_home" || die "mkdir command failed."
 chown "$UID:${GROUPS[0]}" "$cqfd_user_home" || die "chown command failed."
 
 # Add specified groups to cqfd_user
-for g in ${CQFD_GROUPS}; do
+for g in $CQFD_GROUPS; do
 	group=\$(echo "\$g" | cut -d: -f1)
 	gid=\$(echo "\$g" | cut -d: -f2)
 
@@ -459,7 +459,7 @@ for g in ${CQFD_GROUPS}; do
 		groupadd -og "\$gid" -f "\$group" || die "groupadd failed for \$group."
 	fi
 
-	usermod -a -G \$group $cqfd_user || die "usermod command failed while adding group \${group}."
+	usermod -a -G \$group $cqfd_user || die "usermod command failed while adding group \$group."
 done
 
 # run provided command in the working directory
@@ -506,7 +506,7 @@ config_load() {
 		local cqfdrc_dir="$cqfd_project_dir/"
 	fi
 
-	parse_ini_config_file "${cqfdrc_dir}${cqfdrc}"
+	parse_ini_config_file "$cqfdrc_dir$cqfdrc"
 
 	# generate dynamically the list of flavors based on the names of shell
 	# functions reported by the buildtin:
@@ -538,7 +538,7 @@ config_load() {
 		# shellcheck disable=SC2162
 		read -a cqfd_docker <<<"${docker:-$DOCKER}"
 	fi
-	dockerfile="${cqfd_project_dir}/${cqfddir}/${distro:-docker}/Dockerfile"
+	dockerfile="$cqfd_project_dir/$cqfddir/${distro:-docker}/Dockerfile"
 
 	if [ -z "$org" ] || [ -z "$name" ]; then
 		die "Please set project.org and project.name in .cqfdrc"
@@ -558,7 +558,7 @@ config_load() {
 		# shellcheck disable=SC2001
 		format_user=$(sed 's/[^0-9a-zA-Z\-]/_/g' <<<"$USER")
 		dockerfile_hash=$(sha256sum "$dockerfile" | cut -b 1-7)
-		docker_img_name="cqfd${format_user:+_${format_user}}_${org}_${name}_${dockerfile_hash}"
+		docker_img_name="cqfd${format_user:+_$format_user}_$org\_$name\_$dockerfile_hash"
 	fi
 
 	# Adapt things for a specific container
@@ -681,7 +681,7 @@ elif [ -n "$*" ]; then
 fi
 
 if [ -z "$command" ]; then
-	die "No build.command defined in ${cqfdrc}, and no command specified"
+	die "No build.command defined in $cqfdrc, and no command specified"
 fi
 
 docker_run "$command"
