cqfd: remove unnecessary braces in variable expansion
This removes the unnecessary braces surrounding the variable expansion
as everywhere else in the code.

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -165,7 +165,7 @@ image_exists_locally() {
 #
 # - Your project's source directory is always mapped to $cqfd_cwd
 #
-# - Your ~/.ssh directory is mapped to ~${cqfd_user}/.ssh to provide
+# - Your ~/.ssh directory is mapped to ~$cqfd_user/.ssh to provide
 #   access to the ssh keys (your build may pull authenticated git
 #   repos for example).
 #
@@ -236,10 +236,10 @@ docker_run() {
 		for group in $cqfd_extra_groups; do
 			# optional groupd id specified ("name:123")
 			if echo "$group" | grep -qE ":[0-9]+$"; then
-				CQFD_GROUPS+="${group} "
+				CQFD_GROUPS+="$group "
 			else
 				id=$(awk -F: "\$1 == \"$group\" { print \$3 }" /etc/group)
-				CQFD_GROUPS+="${group}:${id} "
+				CQFD_GROUPS+="$group:$id "
 			fi
 		done
 	fi
@@ -428,7 +428,7 @@ mkdir -p "$cqfd_home"
 chown "$UID:${GROUPS[0]}" "$cqfd_home"
 
 # Add specified groups to cqfd_user
-for g in ${CQFD_GROUPS}; do
+for g in $CQFD_GROUPS; do
 	group=\$(echo "\$g" | cut -d: -f1)
 	gid=\$(echo "\$g" | cut -d: -f2)
 
@@ -492,12 +492,12 @@ config_load() {
 		local cqfdrc_dir="$cqfd_project_dir/"
 	fi
 
-	if [ ! -f "${cqfdrc_dir}${cqfdrc}" ]; then
-		die "Unable to find ${cqfdrc_dir}${cqfdrc} - create it or pick one using 'cqfd -f'"
+	if [ ! -f "$cqfdrc_dir$cqfdrc" ]; then
+		die "Unable to find $cqfdrc_dir$cqfdrc - create it or pick one using 'cqfd -f'"
 	fi
 
-	if ! cfg_parser "${cqfdrc_dir}${cqfdrc}"; then
-		die "${cqfdrc_dir}${cqfdrc}: Invalid ini-file!"
+	if ! cfg_parser "$cqfdrc_dir$cqfdrc"; then
+		die "$cqfdrc_dir$cqfdrc: Invalid ini-file!"
 	fi
 
 	# generate dynamically the list of flavors based on the names of shell
@@ -575,7 +575,7 @@ config_load() {
 	fi
 
 	if [ -z "$dockerfile" ]; then
-		dockerfile="${cqfd_project_dir}/${cqfddir}/${distro:-docker}/Dockerfile"
+		dockerfile="$cqfd_project_dir/$cqfddir/${distro:-docker}/Dockerfile"
 	fi
 	if [ ! -f "$dockerfile" ]; then
 		die "$dockerfile not found"
